### PR TITLE
Added normalspacefactory

### PR DESCRIPTION
**Pull request by jbriales**
normalspacefactory(M,x) provides the linear manifold corresponding
to the normal space of a manifold M at a particular point x,
much in the fashion of tangentspacefactory for the tangent space

### CODE REVIEW

**Comment by jbriales** [comment]
This is related to the discussion in the Manopt forum: https://groups.google.com/forum/#!topic/manopttoolbox/68TRSXZH4n4

**Comment by NicolasBoumal** [comment]
Hello Jesus,

Thank you for this proposal. I am a bit puzzled, because the normal space lies somehow outside of what Manopt can capture in full generality. See for example my comment about the projection operation.

I also do not see how to design a generic tool to achieve the same goal, at least not within the manopt framework as it is now. For example, what would this tool do for grassmannfactory? Also, it would fail to work with, say, product manifolds and power manifolds, because their points and vectors are cells.

I'm not arguing that this makes the tool useless, though up until now all tools in the toolbox have the property that they work generically (or at least they should), so users come to expect that.

Could you tell us more about your use case?

Best,
Nicolas

**Comment by jbriales** [comment]
Hi Nicolas!
Well, I see now you're right on your comments regarding this. I wrote this class for using it in the particular case of normal spaces involved [in our previous discussion](https://groups.google.com/forum/#!topic/manopttoolbox/68TRSXZH4n4), but the operations inside do not extend to the variety of manifolds present at Manopt. So, my fault for not considering the more general use scope.
I think we can close this request for now.

Best,
Jesus

**Comment by NicolasBoumal** [comment]
Thanks!

**Pull request closed without merging**
