### PR TITLE
Use sinc in exponential map of sphere and oblique manifold

### PR DESCRIPTION
**Pull request by nkoep**
I noticed that the sphere and oblique manifold implementations of the exponential map tried to avoid evaluating `sin(nrm_td) / nrm_td` explicitly for small `nrm_td`. Using the built-in `sinc`, however, this shouldn't be a problem.

### CODE REVIEW

**Comment by NicolasBoumal** [comment]
Hello Niklas,

Thanks for the suggestion. Unfortunately, `sinc` is not part of "basic" Matlab: it requires the [Signal Processing toolbox](https://www.mathworks.com/help/signal/ref/sinc.html). We prefer to avoid such a dependency.

An alternative could be to add a file sinc.m to Manopt, but it might have undesired side effects for people who intend to use Matlab's sinc. Yet another possibility could be to add a file sinc_manopt.m, and to call that. Then it would be easy to "divert" `sinc_manopt` to `sinc` if that becomes important.

--- I installed the signal processing toolbox just now to see what is in sinc.m, and here it is; nothing fancy really:

```
i=find(x==0);
x(i)= 1; % we don't need to do this if (as is the default) Matlab divides by zero without warning
y = sin(pi*x)./(pi*x);
y(i) = 1;
```

We do not need the scaling by pi. So here is yet another possibility, perhaps my favorite:

We can create a function called `sinxoverx` based on the current manopt code as:

```
function y = sinxoverx(x)
    y = sin(x) ./ x ;
    y(x == 0) = 1;
end
```

Then your calls to `sinc(pi*x)` can be replaced by `sinxoverx(x)` -- does that sound good?

Best,
Nicolas

**Comment by nkoep** [comment]
> 

Ah, I had a feeling that might be the reason. I don't use or have access to matlab so I only checked octave, saw it had a sinc function and assumed it was in matlab by default. Their implementation is also interesting:

```octave
function result = sinc (x)

  if (nargin != 1)
    print_usage ();
  endif

  result = ones (size (x));

  i = (x != 0);

  if (any (i(:)))
    t = pi * x(i);
    result(i) = sin (t) ./ t;
  endif

endfunction
```

I'll update my PR :+1:

**Comment by nkoep** [comment]
I edited the new commit in vim which stripped all whitespaces :sweat_smile: Let me know if you prefer to keep the trailing whitespace in the original files.

**Comment by NicolasBoumal** [comment]
Thanks! -- I put up a fight for the whitespace, but in the end I just merged it as is.

**Pull request merged**
