### PR TITLE
Lie identity

### PR DESCRIPTION
**Pull request by spencerkraisler**
Hi Nicolas, 

Here is my pull request for the lie identity method. For now, I added it to rotationsfactory, unitaryfactory, euclideanfactory, euclideancomplexfactory, complexcirclefactory, powermanifold, and productmanifold. For the latter two methods, I added the lie_identity() method in the way where it performed the necessary Lie identity operations on the individual manifolds. I made sure to match the structure and naming schemes of the other methods. Ofc let me know if you have any questions or you want anything changed. Also, there are more Lie groups I can easily add the lie_identity() method too, but I wanted to make sure what I am in the right direction. 

Also, here is a script I was using to test my changes:

```
clear; close all; clc

k = 3;
n = 5;
M1 = rotationsfactory(n, k);
M2 = unitaryfactory(n, k);
M3 = euclideanfactory(n, k);
M4 = euclideancomplexfactory(n, k);
M5 = complexcirclefactory(n, k);
M6 = powermanifold(M1, n);
M7 = specialeuclideanfactory(n, k);

elements.M1 = M1;
elements.M2 = M2;
elements.M3 = M3;
elements.M4 = M4;
elements.M5 = M5;
elements.M6 = M6;
elements.M7 = M7;
P = productmanifold(elements);

I = P.lie_identity();
for i = 1:7
    Ii = I{i}
end
```

Best,
Spencer

### CODE REVIEW

**Comment by NicolasBoumal** [comment]
Thanks!

Here are some change proposals:

I believe it should be possible to implement all of these "in line", that is, without creating a whole separate function (in a separate file).

E.g., for rotations/unitary factory, you can write:

M.lie_identity = @() repmat(eye(n), [1, 1, k]);

For Euclidean manifolds, e.g., euclideanfactory, you can simply write:

M.lie_identity = @() zeros(dimensions_vec);

Notice the use of `dimensions_vec` rather than m and n: this is explained in the comments re the calling pattern of the factory, and also in the early lines of the code. More generally, for Euclidean manifolds the code for `lie_identity` will likely be the same as for M.zerovec, only without the need for an input "x".

For complexcirclefactory, the code should be `ones(n, m, array_type);` where array_type is needed so that the GPU version of the code works properly.

Good call that you thought to add this to powermanifold`` and productmanifold`` too, as this indeed covers `specialeuclideanfactory`. Small comment there: In powermanifold, line 267 should be:
`function I = lie_identity()`
instead of
`function I = lie_identity`

Nicolas

**Comment by spencerkraisler** [comment]
Hi Nicolas,

Thanks for the suggestions. I implemented it and pushed it to my fork. I believe that's all I have to do for pull requests, right? As before, I still haven't done anything for the other euclidean manifolds, though I am happy to if you want. 

Best,
Spencer

**Comment by NicolasBoumal** [comment]
Thanks! I made some further edits (see commits on this PR): I believe these should work with your test files, but to be checked.

If you can still add support for the other Euclidean manifolds, that would be great. Otherwise, let me know and we'll merge this PR as is.

**Comment by spencerkraisler** [comment]
> Thanks! I made some further edits (see commits on this PR): I believe these should work with your test files, but to be checked.
> 
> 
> 
> If you can still add support for the other Euclidean manifolds, that would be great. Otherwise, let me know and we'll merge this PR as is.

Hi Nicolas,

Sorry for taking awhile with this. I started an internship last month and was super busy. I'll get on this as soon as I have time. 

Best,
Spencer

**Pull request merged**
