### PR TITLE
Added matrix simplex factories

### PR DESCRIPTION
**Pull request by bamdevm**
Given X1, X2, ... Xk Hermitian positive definite matrices, the constraint tackled is X1 + X2 + ... = I.

We propose a Riemannian submanifold structure on this set.

We also propose an extension to the Hermitian case.

It will be great if you could give your suggestions on the improvements.

### CODE REVIEW

**Comment by NicolasBoumal** [comment]
Hello Bamdev,

I'm unclear on what this geometry is.

You mentioned here that it is a Riemannian submanifold. I imagine you mean a Riemannian submanifold of the P^k, where P is the Riemannian manifold of positive definite matrices with the bi-invariant metric?

(Below, C could be the complex or the real numbers)

On the other hand, in the comments in the file, it says that this manifold is a submanifold of (C^(nxn))^k. That's true, but it's potentially misleading. Since P is a submanifold but not a Riemannian submanifold of C^(nxn), surely, M, as a Riemannian submanifold of P^k, is a submanifold of (C^(nxn))^k but not a Riemannian submanifold of the latter. This confusion is reinforced by the comments in the file which talk about the "usual real trace inner product", but that's not the metric I see in the code.

It would be useful to clarify exactly what is the geometry, and what is considered to be the embedding space (or structure space), so that it's clear how proj, egrad2rgrad and ehess2rhess work (among others).

I imagine this is meant to be as follows:

E = (C^(nxn))^k is the embedding space: we have the obvious representation of points there as 3D arrays of size nxnxk.

P = {X in C^(nxn) : X = X* and X positive definite} is a submanifold of C^(nxn). We turn it into a Riemannian manifold (but not a Riemannian submanifold) by equipping it with the bi-invariant metric.

M = {X in P^k : X_1 + ... + X_k = I} is the manifold: it is a Riemannian submanifold of P^k, hence it is also a submanifold (but not a Riemannian submanifold) of E, which is why it's possible to use E as embedding space. We want to use E as embedding space because it's convenient / intuitive.

This should have ramifications for all functions, so it'll need some checking.

Something important: if we do as above, then the embedding space is /all/ k-tuples of matrices of size nxn, not only the symmetric/Hermitian ones. So, projectors need to extract symmetric/Hermitian parts first. Alternatively, one could decide to work with symmetric/Hermitian matrices as embedding space, but this could lead to confusion for users who might forget to ensure symmetry themselves.

Best,
Nicolas

**Comment by bamdevm** [comment]
Hello Nicolas,
Thanks for the feedback.
I will correct the documentation.
Regards,
Bamdev

**Comment by NicolasBoumal** [comment]
Thanks for the update Bamdev.

Can you also address the other point in my comment, specifically, to document for the user what is considered to be the embedding space? This affects many functions (proj, egrad2rgrad, ehess2rhess, tangent2ambient, ...) so the user should know.

Best,
Nicolas

**Comment by bamdevm** [comment]
Hello Nicolas,
let me know if anything needs to be done on the changes.
Regards,
Bamdev

**Comment by NicolasBoumal** [comment]
Hello Bamdev,

You can include a version of the comment as I had in my message earlier (copied below with slight changes) if you think that helps, then move your files from /tests to /manifolds (in the right subfolder), and I'll merge.

Thanks,
Nicolas

~~~

E = (C^(nxn))^k is the embedding space: we have the obvious representation of points there as 3D arrays of size nxnxk. It is equipped with the standard Euclidean metric.

P = {X in C^(nxn) : X = X' and X positive definite} is a submanifold of C^(nxn). We turn it into a Riemannian manifold (but not a Riemannian submanifold) by equipping it with the bi-invariant metric.

M = {X in P^k : X_1 + ... + X_k = I} is the manifold we care about here: it is a Riemannian submanifold of P^k, hence it is also a submanifold (but not a Riemannian submanifold) of E -- our embedding space.

**Comment by bamdevm** [comment]
Done.

**Comment by NicolasBoumal** [comment]
Thanks Bamdev! Merged (and the dev branch was removed--let me know if you need it to be restored.)

**Pull request merged**
